In [7]:
import pandas as pd
import numpy as np

from sklearn.ensemble import IsolationForest

In [8]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Datasets\milk.csv",index_col=0)
df.head()

           water  protein  fat  lactose   ash
Animal
HORSE       90.1      2.6  1.0      6.9  0.35
ORANGUTAN   88.5      1.4  3.5      6.0  0.24
MONKEY      88.4      2.2  2.7      6.4  0.18
DONKEY      90.3      1.7  1.4      6.2  0.40
HIPPO       90.4      0.6  4.5      4.4  0.10

In [9]:
clf = IsolationForest(contamination=0.05, random_state=26)
clf.fit(df)

IsolationForest(contamination=0.05, random_state=26)

In [10]:
predictions = clf.predict(df)
print('%age of outleirs :-'+str((predictions<0).mean()*100)+'%')

%age of outleirs :-8.0%

In [14]:
abn_ind = np.where(predictions < 0)
print('Outliers:')
print(df.index[abn_ind])

Outliers:
Index(['SEAL', 'DOLPHIN'], dtype='object', name='Animal')

# Exercise

In [138]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Cases\Image_Segmentation\Image_Segmentation.csv")
df

,Class,region.centroid.col,region.centroid.row,region.pixel.count,short.line.density.5,short.line.density.2,vedge.mean,vegde.sd,hedge.mean,hedge.sd,intensity.mean,rawred.mean,rawblue.mean,rawgreen.mean,exred.mean,exblue.mean,exgreen.mean,value.mean,saturation.mean,hue-mean
0,BRICKFACE,188,133,9,0.000000,0.0,0.333333,0.266667,0.500000,0.077778,6.666666,8.333334,7.777778,3.888889,5.000000,3.333333,-8.333333,8.444445,0.538580,-0.924817
1,BRICKFACE,105,139,9,0.000000,0.0,0.277778,0.107407,0.833333,0.522222,6.111111,7.555555,7.222222,3.555556,4.333334,3.333333,-7.666666,7.555555,0.532628,-0.965946
2,BRICKFACE,34,137,9,0.000000,0.0,0.500000,0.166667,1.111111,0.474074,5.851852,7.777778,6.444445,3.333333,5.777778,1.777778,-7.555555,7.777778,0.573633,-0.744272
3,BRICKFACE,39,111,9,0.000000,0.0,0.722222,0.374074,0.888889,0.429629,6.037037,7.000000,7.666666,3.444444,2.888889,4.888889,-7.777778,7.888889,0.562919,-1.175773
4,BRICKFACE,16,128,9,0.000000,0.0,0.500000,0.077778,0.666667,0.311111,5.555555,6.888889,6.666666,3.111111,4.000000,3.333333,-7.333334,7.111111,0.561508,-0.985811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,GRASS,36,243,9,0.111111,0.0,1.888889,1.851851,2.000000,0.711110,13.333333,9.888889,12.111111,18.000000,-10.333333,-3.666667,14.000000,18.000000,0.452229,2.368311
205,GRASS,186,218,9,0.000000,0.0,1.166667,0.744444,1.166667,0.655555,13.703704,10.666667,12.666667,17.777779,-9.111111,-3.111111,12.222222,17.777779,0.401347,2.382684
206,GRASS,197,236,9,0.000000,0.0,2.444444,6.829628,3.333333,7.599998,16.074074,13.111111,16.666668,18.444445,-8.888889,1.777778,7.111111,18.555555,0.292729,2.789800
207,GRASS,208,240,9,0.111111,0.0,1.055556,0.862963,2.444444,5.007407,14.148149,10.888889,13.000000,18.555555,-9.777778,-3.444444,13.222222,18.555555,0.421621,2.392487
208,GRASS,223,185,9,0.000000,0.0,0.500000,0.349603,2.388889,2.080776,12.962963,11.555555,9.777778,17.555555,-4.222222,-9.555555,13.777778,17.555555,0.445418,1.838850

In [139]:
X , y = df.drop('Class',axis=1) , df['Class']

In [140]:
labels = y.unique()

In [141]:
clf = IsolationForest(contamination=0.05, random_state=26)
clf.fit(X)

IsolationForest(contamination=0.05, random_state=26)

In [142]:
predictions = clf.predict(X)
print('%age of outleirs : '+str((predictions<0).mean()*100)+'%')

%age of outleirs : 5.263157894736842%

In [143]:
predictions

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1, -1,  1, -1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1, -1,  1,  1,
        1,  1,  1, -1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1])

In [144]:
pd.crosstab(y,predictions)

col_0      -1   1
Class
BRICKFACE   0  29
CEMENT      1  29
FOLIAGE     4  26
GRASS       0  30
PATH        1  29
SKY         5  25
WINDOW      0  30

In [145]:
# df['Prediction'] = predictions

In [146]:
# outliers = df[df['Prediction'] < 0]['Class']
# outliers.value_counts()

# With Outliers

In [147]:
from sklearn.model_selection import StratifiedKFold , GridSearchCV
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=26)
param = {
    'solver':['saga','newton-cg','sag','newton-cholesky','lbfgs'],
    'C':np.linspace(0.001,5,10)
}

gcv = GridSearchCV(lr, param_grid=param, scoring='neg_log_loss', cv=kfold, n_jobs=-1)
gcv.fit(X,y)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=26, shuffle=True),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.00000000e-03, 5.56444444e-01, 1.11188889e+00, 1.66733333e+00,
       2.22277778e+00, 2.77822222e+00, 3.33366667e+00, 3.88911111e+00,
       4.44455556e+00, 5.00000000e+00]),
                         'solver': ['saga', 'newton-cg', 'sag',
                                    'newton-cholesky', 'lbfgs']},
             scoring='neg_log_loss')

In [148]:
gcv.best_params_,gcv.best_score_

({'C': np.float64(0.5564444444444444), 'solver': 'newton-cholesky'},
 np.float64(-0.48076881996119897))

# Remove Outliers

In [149]:
df = df[predictions==1]

In [150]:
df

,Class,region.centroid.col,region.centroid.row,region.pixel.count,short.line.density.5,short.line.density.2,vedge.mean,vegde.sd,hedge.mean,hedge.sd,intensity.mean,rawred.mean,rawblue.mean,rawgreen.mean,exred.mean,exblue.mean,exgreen.mean,value.mean,saturation.mean,hue-mean
0,BRICKFACE,188,133,9,0.000000,0.0,0.333333,0.266667,0.500000,0.077778,6.666666,8.333334,7.777778,3.888889,5.000000,3.333333,-8.333333,8.444445,0.538580,-0.924817
1,BRICKFACE,105,139,9,0.000000,0.0,0.277778,0.107407,0.833333,0.522222,6.111111,7.555555,7.222222,3.555556,4.333334,3.333333,-7.666666,7.555555,0.532628,-0.965946
2,BRICKFACE,34,137,9,0.000000,0.0,0.500000,0.166667,1.111111,0.474074,5.851852,7.777778,6.444445,3.333333,5.777778,1.777778,-7.555555,7.777778,0.573633,-0.744272
3,BRICKFACE,39,111,9,0.000000,0.0,0.722222,0.374074,0.888889,0.429629,6.037037,7.000000,7.666666,3.444444,2.888889,4.888889,-7.777778,7.888889,0.562919,-1.175773
4,BRICKFACE,16,128,9,0.000000,0.0,0.500000,0.077778,0.666667,0.311111,5.555555,6.888889,6.666666,3.111111,4.000000,3.333333,-7.333334,7.111111,0.561508,-0.985811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,GRASS,36,243,9,0.111111,0.0,1.888889,1.851851,2.000000,0.711110,13.333333,9.888889,12.111111,18.000000,-10.333333,-3.666667,14.000000,18.000000,0.452229,2.368311
205,GRASS,186,218,9,0.000000,0.0,1.166667,0.744444,1.166667,0.655555,13.703704,10.666667,12.666667,17.777779,-9.111111,-3.111111,12.222222,17.777779,0.401347,2.382684
206,GRASS,197,236,9,0.000000,0.0,2.444444,6.829628,3.333333,7.599998,16.074074,13.111111,16.666668,18.444445,-8.888889,1.777778,7.111111,18.555555,0.292729,2.789800
207,GRASS,208,240,9,0.111111,0.0,1.055556,0.862963,2.444444,5.007407,14.148149,10.888889,13.000000,18.555555,-9.777778,-3.444444,13.222222,18.555555,0.421621,2.392487
208,GRASS,223,185,9,0.000000,0.0,0.500000,0.349603,2.388889,2.080776,12.962963,11.555555,9.777778,17.555555,-4.222222,-9.555555,13.777778,17.555555,0.445418,1.838850

In [151]:
X , y = df.drop('Class',axis=1) , df['Class']

In [152]:
lr = LogisticRegression()
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=26)
param = {
    'solver':['saga','newton-cg','sag','newton-cholesky','lbfgs'],
    'C':np.linspace(0.001,5,10)
}

gcv = GridSearchCV(lr, param_grid=param, scoring='neg_log_loss', cv=kfold, n_jobs=-1)
gcv.fit(X,y)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=26, shuffle=True),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.00000000e-03, 5.56444444e-01, 1.11188889e+00, 1.66733333e+00,
       2.22277778e+00, 2.77822222e+00, 3.33366667e+00, 3.88911111e+00,
       4.44455556e+00, 5.00000000e+00]),
                         'solver': ['saga', 'newton-cg', 'sag',
                                    'newton-cholesky', 'lbfgs']},
             scoring='neg_log_loss')

In [153]:
gcv.best_params_,gcv.best_score_

({'C': np.float64(0.001), 'solver': 'newton-cg'},
 np.float64(-0.4760310518194501))

# Exercise

In [181]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Cases\Satellite_Imaging\Satellite.csv",sep=';')
df.sample(5)

,x.1,x.2,x.3,x.4,x.5,x.6,x.7,x.8,x.9,x.10,...,x.28,x.29,x.30,x.31,x.32,x.33,x.34,x.35,x.36,classes
2666,67,115,129,101,67,120,124,97,70,115,...,99,68,116,122,99,68,116,128,99,red soil
4622,43,31,128,135,43,31,128,135,46,34,...,133,46,32,122,125,46,34,122,125,cotton crop
3423,63,75,76,59,66,75,76,63,70,79,...,87,89,106,110,87,85,106,110,87,grey soil
4286,67,102,114,90,70,106,119,94,67,106,...,92,71,103,118,96,68,107,122,96,red soil
5748,67,73,82,72,71,84,86,75,75,81,...,72,76,85,94,76,72,89,94,72,very damp grey soil

In [182]:
X , y = df.drop('classes',axis=1) , df['classes']

In [157]:
lr = LogisticRegression()
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=26)
param = {
    'solver':['saga','newton-cg','sag','newton-cholesky','lbfgs'],
    'C':np.linspace(0.001,5,10)
}

gcv = GridSearchCV(lr, param_grid=param, scoring='neg_log_loss', cv=kfold, n_jobs=-1)
gcv.fit(X,y)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=26, shuffle=True),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.00000000e-03, 5.56444444e-01, 1.11188889e+00, 1.66733333e+00,
       2.22277778e+00, 2.77822222e+00, 3.33366667e+00, 3.88911111e+00,
       4.44455556e+00, 5.00000000e+00]),
                         'solver': ['saga', 'newton-cg', 'sag',
                                    'newton-cholesky', 'lbfgs']},
             scoring='neg_log_loss')

In [162]:
gcv.best_params_,gcv.best_score_

({'C': np.float64(0.001), 'solver': 'newton-cholesky'},
 np.float64(-0.35961804302178474))

## Removing Outliers

In [183]:
model = IsolationForest(contamination=0.05, random_state=26)
model.fit(X)

IsolationForest(contamination=0.05, random_state=26)

In [184]:
prediction = model.predict(X)
print('Outliers % :- ',(prediction<0).mean()*100)
# (prediction<0).any()  -> to check any true value in numpy array

Outliers % :-  5.003885003885004

In [185]:
df = df[prediction == 1]

In [186]:
X , y = df.drop('classes',axis=1) , df['classes']

In [ ]:
lr = LogisticRegression()
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=26)
param = {
    'solver':['saga','newton-cg','sag','newton-cholesky','lbfgs'],
    'C':np.linspace(0.001,5,10)
}

gcv = GridSearchCV(lr, param_grid=param, scoring='neg_log_loss', cv=kfold, n_jobs=-1)
gcv.fit(X,y)

In [ ]:
gcv.best_params_,gcv.best_score_